name: SBDD
channels:
  - pytorch3d
  - pyg
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20230802.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - anyio=4.2.0
  - arrow=1.2.3
  - async-timeout=4.0.3
  - attrs=23.1.0
  - backoff=2.2.1
  - beautifulsoup4=4.12.3
  - blas=1.0
  - blessed=1.20.0
  - blinker=1.6.2
  - boto3=1.34.82
  - botocore=1.34.82
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - croniter=1.3.7
  - cryptography=42.0.5
  - cudatoolkit=11.5.1
  - dataclasses=0.8
  - dateutils=0.6.12
  - deepdiff=7.0.1
  - docker-pycreds=0.4.0
  - exceptiongroup=1.2.0
  - fastapi=0.103.0
  - ffmpeg=4.2.2
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - fvcore=0.1.5.post20220512
  - gitdb=4.0.7
  - gitpython=3.1.43
  - gmp=6.2.1
  - gnutls=3.6.15
  - grpc-cpp=1.48.2
  - gtest=1.14.0
  - h11=0.14.0
  - idna=3.7
  - inquirer=3.1.4
  - intel-openmp=2023.1.0
  - iopath=0.1.9
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - jmespath=1.0.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuv=1.48.0
  - libvpx=1.7.0
  - libwebp-base=1.3.2
  - lightning=2.0.9.post0
  - lightning-cloud=0.5.57
  - lightning-utilities=0.9.0
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.4
  - ncurses=6.4
  - nettle=3.7.3
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.14
  - ordered-set=4.1.0
  - orjson=3.9.15
  - pathtools=0.1.2
  - pip=24.0
  - portalocker=2.3.0
  - promise=2.3
  - protobuf=3.20.3
  - psutil=5.9.0
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0post0
  - python-editor=1.0.4
  - python-multipart=0.0.6
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-cluster=1.6.0
  - pytorch-lightning=1.7.7
  - pytorch-mutex=1.0
  - pytorch3d=0.7.3
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readchar=4.0.5
  - readline=8.2
  - requests=2.32.2
  - requests-oauthlib=2.0.0
  - rich=13.7.1
  - rsa=4.7.2
  - s3transfer=0.10.1
  - sentry-sdk=1.9.0
  - setproctitle=1.2.2
  - setuptools=69.5.1
  - shortuuid=1.0.11
  - six=1.16.0
  - smmap=4.0.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - starlette=0.27.0
  - starsessions=1.3.0
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - termcolor=2.1.0
  - tk=8.6.14
  - torchaudio=0.11.0
  - torchmetrics=0.11.4
  - torchvision=0.12.0
  - tqdm=4.66.4
  - typing_extensions=4.11.0
  - urllib3=1.26.19
  - uvicorn=0.20.0
  - wandb=0.13.5
  - websocket-client=1.8.0
  - websockets=10.4
  - wheel=0.43.0
  - x264=1!157.20191217
  - xz=5.4.6
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - alabaster==0.7.13
    - asttokens==2.2.1
    - autodocktools-py3==1.5.7.post1+12.ga62a5d9
    - babel==2.12.1
    - backcall==0.2.0
    - bel-resources==0.0.3
    - biopython==1.81
    - bioregistry==0.8.19
    - biotite==0.40.0
    - cachetools==5.3.0
    - chemprop==0.0.0
    - click-plugins==1.1.1
    - cloudpickle==2.2.1
    - comm==0.1.3
    - contourpy==1.0.7
    - curies==0.5.3
    - cycler==0.11.0
    - datamol==0.12.5
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.9
    - docstring-parser==0.15
    - docutils==0.19
    - easydict==1.10
    - einops==0.8.0
    - executing==1.2.0
    - fasteners==0.19
    - flask==2.2.3
    - fonttools==4.38.0
    - freetype-py==2.4.0
    - future==0.18.3
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - greenlet==2.0.2
    - griddataformats==1.0.2
    - grpcio==1.54.0
    - humanize==4.6.0
    - hydride==1.1.2
    - hyperopt==0.2.7
    - imageio==2.25.1
    - imagesize==1.4.1
    - importlib-metadata==6.1.0
    - importlib-resources==5.10.2
    - ipykernel==6.22.0
    - ipython==8.12.0
    - ipywidgets==8.0.6
    - jedi==0.18.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter-client==8.1.0
    - jupyter-core==5.3.0
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - lmdb==1.4.0
    - loguru==0.7.2
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.7.0
    - matplotlib-inline==0.1.6
    - mda-xdrlib==0.2.0
    - mdanalysis==2.7.0
    - meeko==0.2
    - mesh-to-sdf==0.0.14
    - mmtf-python==1.1.3
    - more-click==0.1.2
    - more-itertools==9.1.0
    - mrcfile==1.5.3
    - msgpack==1.1.0
    - multiprocess==0.70.17
    - multisplitby==0.0.1
    - mypy-extensions==1.0.0
    - nest-asyncio==1.5.6
    - networkx==3.0
    - nglview==3.0.3
    - numpy==1.24.4
    - numpydoc==1.5.0
    - oddt==0.7
    - openbabel-wheel==3.1.1.19
    - openeye-toolkits==2023.1.1
    - openeye-toolkits-python3-linux-x64==2023.1.1
    - packaging==23.0
    - pandas==1.5.3
    - pandas-flavor==0.5.0
    - parso==0.8.3
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - platformdirs==3.2.0
    - posecheck==1.3.1
    - prolif==2.0.3
    - prompt-toolkit==3.0.38
    - psycopg2-binary==2.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py3dmol==2.0.1.post1
    - py4j==0.10.9.7
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybel==0.15.5
    - pydantic==1.10.7
    - pyglet==2.0.8
    - pygments==2.14.0
    - pyopengl==3.1.0
    - pyparsing==3.1.2
    - pyrender==0.1.45
    - pyrsistent==0.19.3
    - pystow==0.5.0
    - pytrie==0.4.0
    - pytz==2022.7.1
    - pywavelets==1.4.1
    - pyzmq==25.0.2
    - ratelimit==2.2.1
    - rdkit==2022.9.4
    - requests-file==1.5.1
    - rtree==1.0.1
    - scikit-image==0.20.0
    - scikit-learn==1.2.1
    - scipy==1.9.1
    - seaborn==0.12.2
    - selfies==2.1.2
    - sklearn==0.0.post5
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - sphinx==6.1.3
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlalchemy==2.0.11
    - stack-data==0.6.2
    - tensorboard==2.12.3
    - tensorboardx==2.6
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - torch==1.13.1
    - torch-geometric==2.4.0
    - torch-scatter==2.0.9
    - torch-sparse==0.6.13
    - tornado==6.2
    - traitlets==5.9.0
    - trimesh==3.22.0
    - typed-argument-parser==1.8.0
    - typing-extensions==4.5.0
    - typing-inspect==0.8.0
    - tzdata==2024.2
    - vina==1.2.5
    - wcwidth==0.2.6
    - webencodings==0.5.1
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.7
    - xarray==2023.3.0
    - zipp==3.15.0
